# Generated by Django 4.2.4 on 2023-08-15 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=128, verbose_name='신고 제목')),
                ('reporter_name', models.CharField(max_length=8, verbose_name='신고자 이름')),
                ('reporter_contact', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='유효한 전화번호 형식이 아닙니다.', regex='^(\\d{2,3}-)?\\d{3,4}-\\d{4}$')], verbose_name='신고자 연락처')),
                ('reporter_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='유효한 이메일 주소 형식이 아닙니다.')], verbose_name='신고자 메일')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='신고접수시간')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='신고수정시간')),
                ('accident_time', models.DateTimeField(null=True, verbose_name='사고발생시간')),
                ('cognition_time', models.DateTimeField(null=True, verbose_name='사고인지시점')),
                ('total_pc', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='양수만 입력 가능합니다.')], verbose_name='전체pc대수')),
                ('total_server', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='양수만 입력 가능합니다.')], verbose_name='전체서버대수')),
                ('damaged_pc', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='양수만 입력 가능합니다.')], verbose_name='피해pc대수')),
                ('damaged_server', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='양수만 입력 가능합니다.')], verbose_name='피해서버대수')),
                ('accident_details', models.TextField(blank=True, verbose_name='사고내용')),
                ('action_details', models.TextField(blank=True, verbose_name='조치사항')),
                ('encrypted_file_ext', models.CharField(max_length=8, verbose_name='암호화파일 확장자명')),
                ('current_status', models.CharField(choices=[('단순업무장애', '단순업무장애'), ('주요서비스장애', '주요서비스장애'), ('개인정보유출', '개인정보유출'), ('기타', '기타')], max_length=16, verbose_name='피해현황')),
                ('backup_status', models.CharField(choices=[('전체백업', '전체백업'), ('일부백업', '일부백업'), ('백업이 있으나 감염', '백업이 있으나 감염'), ('없음', '없음'), ('기타', '기타')], max_length=16, verbose_name='백업유무')),
                ('ransom_status', models.BooleanField(verbose_name='협박유무')),
                ('report_status', models.BooleanField(verbose_name='경찰신고 유무')),
                ('is_deleted', models.BooleanField(verbose_name='신고삭제 유무')),
            ],
            options={
                'db_table': 'report',
            },
        ),
    ]
