# Generated by Django 4.2.4 on 2023-08-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='신고삭제 유무'),
        ),
    ]
