# Generated by Django 4.2.4 on 2023-08-16 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_alter_report_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='신고 계정'),
        ),
    ]
